version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
    ports:
      - "3306:3306"
    volumes:
      - data_mysql:/var/lib/db

volumes:
  data_mysql: